apiVersion: v1
kind: Service
metadata:
  name: {{ include "exchange-app.fullname" . }}
  labels:
    {{- include "exchange-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "exchange-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
