services:
  apigateway-service:
    build:
      context: .
    container_name: apigateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
