global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'apigateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'apigateway-service'

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5002']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'account-service'

  - job_name: 'currency-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'currency-service'

  - job_name: 'exchange-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5003']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'exchange-service'

  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5004']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'transaction-service'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5005']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'notification-service'
